architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

repositories {
    maven { url = "https://maven.terraformersmc.com/" } // mod-menu
}

dependencies {
    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"

    common(project(path: ':common')) { transitive false }

    implementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_fabric_version}"
    implementation "com.terraformersmc:modmenu:${rootProject.mod_menu_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

jar {
    archiveClassifier = 'raw'
}

task shadowJar(type: Jar) {
    dependsOn(jar, project(':common').tasks.named('transformProductionFabric'))
    archiveClassifier = null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.output)
    from({ zipTree(project(':common').tasks.named('transformProductionFabric').get().archiveFile) })
    from rootProject.file("LICENSE")
}

assemble.dependsOn shadowJar

publishing {
    publications {
        mavenJava {
            artifact(shadowJar)
        }
    }
}
