# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=1.7.0
maven_group=io.devbobcorn.acrylic
archives_name=acrylic
enabled_platforms=fabric,neoforge

# Common Dependencies
minecraft_version=26.1

# Fabric-Specific Dependencies
fabric_loader_version=0.19.2
fabric_api_version=0.148.0+26.1.2
mod_menu_version=18.0.0-alpha.8
yacl_fabric_version=3.9.3+26.1-fabric

# NeoForge-Specific Dependencies
neoforge_version=21.6.20-beta
yacl_neoforge_version=3.9.3+26.1-neoforge
