# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version=1.8.6
maven_group=io.devbobcorn.acrylic
archives_name=acrylic
enabled_platforms=fabric,neoforge

# Common Dependencies
minecraft_version=26.2

# Fabric-Specific Dependencies
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2
mod_menu_version=20.0.0-beta.2
yacl_fabric_version=3.9.4+26.2-fabric

# NeoForge-Specific Dependencies
neoforge_version=26.2.0.3-beta
yacl_neoforge_version=3.9.4+26.2-neoforge
