architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }

    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
        content { includeGroup "thedarkcolour" }
    }

    maven { url = "https://maven.quiltmc.org/repository/release" }
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common')) { transitive false }
    
    implementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_neoforge_version}"
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

jar {
    archiveClassifier = 'raw'
}

task shadowJar(type: Jar) {
    dependsOn(jar, project(':common').tasks.named('transformProductionNeoForge'))
    archiveClassifier = null
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.output)
    from({ zipTree(project(':common').tasks.named('transformProductionNeoForge').get().archiveFile) })
    from rootProject.file("LICENSE")
}

assemble.dependsOn shadowJar

publishing {
    publications {
        mavenJava {
            artifact(shadowJar)
        }
    }
}
